import { caseLocales, translatedRoomSuffix } from './case-locales.js?v=20260929-4';

export const locales = [
  { code: 'en', label: 'English', dir: 'ltr' },
  { code: 'fr', label: 'Français', dir: 'ltr' },
  { code: 'es', label: 'Español', dir: 'ltr' },
  { code: 'ar', label: 'العربية', dir: 'rtl' },
  { code: 'ru', label: 'Русский', dir: 'ltr' },
  { code: 'zh-CN', label: '简体中文', dir: 'ltr' },
  { code: 'zh-TW', label: '繁體中文', dir: 'ltr' },
];

const copy = {
  en: {
    settings: 'Settings', help: 'How to play', close: 'Close', theme: 'Appearance', light: 'Light', dark: 'Dark', toggle: 'toggle', clock: 'Clock', visible: 'Visible', hidden: 'Hidden', language: 'Language', done: 'Done', gotIt: 'Got it', rules: 'The rules of the case', preferences: 'Preferences', musicOn:'Play background music', musicOff:'Stop background music',
    heroEyebrow: 'A game of logic & murder', heroOne: 'Every clue tells a story.', heroTwo: 'Every story ends in murder.', heroDescription: 'Read between the lines. Find the killer. Case closed.', investigation: 'Your investigation', caseFiles: 'Case files', all: 'All', veryEasy: 'Very Easy', easy: 'Easy', medium: 'Medium', hard: 'Hard', expert: 'Expert', release: 'Release date', difficulty: 'Difficulty', title: 'Title', recent: 'Recently played', popular: 'Popular', status: 'Status', caseNo: 'Case No.', solved: 'Solved', revisit: 'Revisit case', open: 'Open case', viewAll: 'View all cases', copyright: '© Murdoku-inspired · independent fan project', collection: 'An original collection of logic mysteries', howToPlayLink: 'How to play', back: 'Cases', row: 'row', column: 'column', suspects: 'Suspects', suspectPrompt: 'Tap a card to select · then tap a square', evidence: 'The evidence', clues: 'clues', markImpossible: 'Mark impossible', clear: 'Clear board', undo: 'Undo', hint: 'Hint', submit: 'Submit', selectPerson: 'Select {name}',
    collectionStats:'Case collection progress', totalCases:'{count} cases', solvedCount:'{count} solved', progressCount:'{count} in progress', inProgress:'In progress', caseAvailable:'Case available · open dossier', continueCase:'Continue case', solvedBoard:'Solved case board', completedIn:'Solved in {time}', caseClosed:'CASE CLOSED', solvedHeadline:'The truth is in the file.', backToCases:'Back to cases', nextCase:'Next case', revisitCaseNamed:'Revisit {title}', openCaseNamed:'Open {title}',
    conflict: 'One person per row and column. Move the conflicting person first.', allCorrect: 'All placements are correct.', incomplete:'Place everyone before submitting.', solvedMessage: 'Case solved. {culprit} was alone with the victim in the {room}.', incorrect: 'Not quite. Re-read the evidence and try again.', clueRowRoom: '{person} was in row {row}, in the {room}.', clueColumn: 'They were in column {column}.', clueColumnPair: 'They were in the same two-column section as {anchor}; the two never shared a column.', clueRole: '{role}.', clueVictim: 'The victim was alone with the murderer in that room.',
    helpIntro:'Use the evidence to place everyone on the scene. Each person must occupy a different row and column. Thick walls outline the rooms; the victim shares a room with exactly one suspect.', helpSelect: 'Select a suspect, then tap a square to place them.', helpX: 'Use × to mark an impossible square.', helpUndo: 'Undo reverses the last move. Hint reveals a correct placement.', helpSubmit: 'Submit checks the full board and identifies the murderer.',
    rooms: {
      'Front hall':'Front hall','Living room':'Living room','Garden':'Garden','Studio':'Studio','Atrium':'Atrium','Courtyard':'Courtyard','Conservatory':'Conservatory','Chapel':'Chapel','Cellar':'Cellar','Vault':'Vault','Main gallery':'Main gallery','Office':'Office','Room 12':'Room 12','Front desk':'Front desk','Parking lot':'Parking lot','Soundstage':'Soundstage','Wardrobe':'Wardrobe','Prop room':'Prop room',
      Kitchen:'Kitchen','Dining room':'Dining room','Library':'Library','Ballroom':'Ballroom','Study':'Study','Bedroom':'Bedroom','Guest room':'Guest room','Basement':'Basement','Attic':'Attic','Greenhouse':'Greenhouse','Terrace':'Terrace','Pool':'Pool','Garage':'Garage','Workshop':'Workshop','Foyer':'Foyer','Library annex':'Library annex','Theater':'Theater','Theatre':'Theatre','Dressing room':'Dressing room','Control room':'Control room','Lounge':'Lounge','Restaurant':'Restaurant','Bar':'Bar','Lobby':'Lobby','Elevator':'Elevator','Corridor':'Corridor','Hallway':'Hallway','Boiler room':'Boiler room','Roof':'Roof','Rooftop':'Rooftop','Dock':'Dock','Warehouse':'Warehouse','Archive':'Archive','Archives':'Archives','Laboratory':'Laboratory','Lab':'Lab','Garden shed':'Garden shed','Veranda':'Veranda','Balcony':'Balcony','Billiard room':'Billiard room','Music room':'Music room','Music hall':'Music hall','Sitting room':'Sitting room','Pantry':'Pantry','Laundry room':'Laundry room','Train car':'Train car','Platform':'Platform','Ticket hall':'Ticket hall','Cabin':'Cabin','Deck':'Deck','Engine room':'Engine room','Bridge':'Bridge','Dining car':'Dining car','Observatory':'Observatory','Clinic':'Clinic','Emergency room':'Emergency room','Ward':'Ward','Morgue':'Morgue','Evidence room':'Evidence room','Interview room':'Interview room','Police station':'Police station','Pier':'Pier','Beach':'Beach','Forest':'Forest','Cottage':'Cottage','Pavilion':'Pavilion','Courthouse':'Courthouse','Church':'Church','Monastery':'Monastery','Museum':'Museum','Exhibition hall':'Exhibition hall','Gallery':'Gallery','Main hall':'Main hall','Side hall':'Side hall','Private room':'Private room','Smoking room':'Smoking room','Secret room':'Secret room','Secret passage':'Secret passage','Wine cellar':'Wine cellar','Wine room':'Wine room','Tea room':'Tea room','Map room':'Map room','Clock tower':'Clock tower','West wing':'West wing','East wing':'East wing'
    },
    roles: {
      'Beside the delivery box':'Beside the delivery box','Sitting in the chair':'Sitting in the chair','Only person on the carpet':'Only person on the carpet','A houseguest':'A houseguest','Beside the potted plant':'Beside the potted plant','The victim':'The victim','Interior designer':'Interior designer','Contractor':'Contractor','Daughter':'Daughter','Art dealer':'Art dealer','Groundskeeper':'Groundskeeper','Housekeeper':'Housekeeper','Nephew':'Nephew','Medium':'Medium','Physician':'Physician','Neighbor':'Neighbor','Curator':'Curator','Guard':'Guard','Artist':'Artist','Collector':'Collector','Conservator':'Conservator','Night clerk':'Night clerk','Truck driver':'Truck driver','Sister':'Sister','Mechanic':'Mechanic','Traveler':'Traveler','Lead actor':'Lead actor','Director':'Director','Editor':'Editor','Stunt double':'Stunt double','Producer':'Producer',
      Butler:'Butler',Maid:'Maid','Private detective':'Private detective','Detective':'Detective','Police officer':'Police officer','Inspector':'Inspector','Doctor:' : 'Doctor','Doctor':'Doctor','Nurse':'Nurse','Surgeon':'Surgeon','Lawyer':'Lawyer','Attorney':'Attorney','Judge':'Judge','Writer':'Writer','Novelist':'Novelist','Journalist':'Journalist','Reporter':'Reporter','Photographer':'Photographer','Professor':'Professor','Teacher':'Teacher','Student':'Student','Scientist':'Scientist','Researcher':'Researcher','Chef':'Chef','Cook':'Cook','Waiter':'Waiter','Waitress':'Waitress','Bartender':'Bartender','Pilot':'Pilot','Captain':'Captain','Sailor':'Sailor','Engineer':'Engineer','Mechanic':'Mechanic','Driver':'Driver','Chauffeur':'Chauffeur','Actor':'Actor','Actress':'Actress','Singer':'Singer','Musician':'Musician','Composer':'Composer','Dancer':'Dancer','Painter':'Painter','Sculptor':'Sculptor','Architect':'Architect','Designer':'Designer','Business partner':'Business partner','Businessman':'Businessman','Businesswoman':'Businesswoman','CEO':'CEO','Assistant':'Assistant','Secretary':'Secretary','Caretaker':'Caretaker','Gardener':'Gardener','Farmer':'Farmer','Rancher':'Rancher','Banker':'Banker','Accountant':'Accountant','Investor':'Investor','Heir':'Heir','Heiress':'Heiress','Son':'Son','Brother':'Brother','Mother':'Mother','Father':'Father','Wife':'Wife','Husband':'Husband','Cousin':'Cousin','Uncle':'Uncle','Aunt':'Aunt','Granddaughter':'Granddaughter','Grandson':'Grandson','Grandmother':'Grandmother','Grandfather':'Grandfather','Friend':'Friend','Guest':'Guest','Houseguest':'Houseguest','Neighbor':'Neighbor','Owner':'Owner','Client':'Client','Customer':'Customer','Security guard':'Security guard','Bodyguard':'Bodyguard','Valet':'Valet','Bellhop':'Bellhop','Receptionist':'Receptionist','Librarian':'Librarian','Priest':'Priest','Pastor':'Pastor','Nun':'Nun','Monk':'Monk','Medium':'Medium','Fortune teller':'Fortune teller','Magician':'Magician','Thief':'Thief','Smuggler':'Smuggler','Victim':'Victim'
    },
  },
  fr: {
    settings:'Paramètres',help:'Comment jouer',close:'Fermer',theme:'Apparence',light:'Clair',dark:'Sombre',toggle:'changer',clock:'Chronomètre',visible:'Visible',hidden:'Masqué',language:'Langue',done:'Terminé',gotIt:'Compris',rules:'Les règles de l’enquête',preferences:'Préférences',musicOn:'Lancer la musique de fond',musicOff:'Arrêter la musique de fond',
    heroEyebrow:'Un jeu de logique et de meurtre',heroOne:'Chaque indice raconte une histoire.',heroTwo:'Chaque histoire finit par un meurtre.',heroDescription:'Lisez entre les lignes. Trouvez le coupable. Affaire classée.',investigation:'Votre enquête',caseFiles:'Dossiers',all:'Tout',veryEasy:'Très facile',easy:'Facile',medium:'Moyen',hard:'Difficile',expert:'Expert',release:'Date de sortie',difficulty:'Difficulté',title:'Titre',recent:'Récemment jouées',popular:'Populaires',status:'Statut',caseNo:'AFFAIRE N°',solved:'RÉSOLUE',revisit:'REVOIR L’AFFAIRE',open:'OUVRIR L’AFFAIRE',viewAll:'VOIR TOUTES LES AFFAIRES',copyright:'© Murdoku-inspired · independent fan project',collection:'Une collection originale de mystères logiques',howToPlayLink:'COMMENT JOUER',back:'AFFAIRES',row:'ligne',column:'colonne',suspects:'Suspects',suspectPrompt:'Touchez une carte, puis une case',evidence:'Les indices',clues:'INDICES',markImpossible:'Marquer une case impossible',clear:'Effacer la grille',undo:'Annuler',hint:'Indice',submit:'Valider',selectPerson:'Sélectionner {name}',
    collectionStats:'Avancement des dossiers', totalCases:'{count} affaires', solvedCount:'{count} résolues', progressCount:'{count} en cours', inProgress:'En cours', caseAvailable:'Dossier disponible · ouvrir', continueCase:'Continuer l’affaire', solvedBoard:'Grille résolue', completedIn:'Résolue en {time}', caseClosed:'AFFAIRE CLASSÉE', solvedHeadline:'La vérité est au dossier.', backToCases:'Retour aux affaires', nextCase:'Affaire suivante', revisitCaseNamed:'Revoir {title}', openCaseNamed:'Ouvrir {title}',
    conflict:'Une personne par ligne et par colonne. Déplacez d’abord la personne qui gêne.',allCorrect:'Tous les placements sont corrects.',incomplete:'Placez tout le monde avant de valider.',solvedMessage:'Affaire résolue. {culprit} était seul avec la victime dans {room}.',incorrect:'Pas encore. Relisez les indices et réessayez.',clueRowRoom:'{person} se trouvait à la ligne {row}, dans {room}.',clueColumn:'La personne était dans la colonne {column}.',clueColumnPair:'La personne se trouvait dans les deux mêmes colonnes que {anchor} ; leurs colonnes étaient différentes.',clueRole:'{role}.',clueVictim:'La victime était seule avec le meurtrier dans cette pièce.',
    helpIntro:'Utilisez les indices pour placer tout le monde sur la scène. Chaque personne doit occuper une ligne et une colonne différentes. Les murs épais délimitent les pièces ; la victime partage une pièce avec un seul suspect.',helpSelect:'Sélectionnez un suspect, puis touchez une case pour le placer.',helpX:'Utilisez × pour marquer une case impossible.',helpUndo:'Annuler revient sur le dernier coup. Indice révèle un placement correct.',helpSubmit:'Valider vérifie la grille et identifie le meurtrier.',
    rooms:{'Front hall':'Entrée','Living room':'Salon','Garden':'Jardin','Studio':'Atelier','Atrium':'Atrium','Courtyard':'Cour','Conservatory':'Véranda','Chapel':'Chapelle','Cellar':'Cave','Vault':'Coffre-fort','Main gallery':'Grande galerie','Office':'Bureau','Room 12':'Chambre 12','Front desk':'Réception','Parking lot':'Parking','Soundstage':'Plateau de tournage','Wardrobe':'Costumes','Prop room':'Réserve des accessoires',Kitchen:'Cuisine','Dining room':'Salle à manger',Library:'Bibliothèque',Ballroom:'Salle de bal',Study:'Cabinet',Bedroom:'Chambre','Guest room':'Chambre d’amis',Basement:'Sous-sol',Attic:'Grenier',Greenhouse:'Serre',Terrace:'Terrasse',Pool:'Piscine',Garage:'Garage',Workshop:'Atelier',Foyer:'Hall',Theater:'Théâtre',Theatre:'Théâtre','Dressing room':'Loge','Control room':'Salle de contrôle',Lounge:'Salon',Restaurant:'Restaurant',Bar:'Bar',Lobby:'Hall',Elevator:'Ascenseur',Corridor:'Couloir',Hallway:'Couloir','Boiler room':'Chaufferie',Roof:'Toit',Rooftop:'Toit-terrasse',Dock:'Quai',Warehouse:'Entrepôt',Archive:'Archives',Archives:'Archives',Laboratory:'Laboratoire',Lab:'Laboratoire','Garden shed':'Abri de jardin',Veranda:'Véranda',Balcony:'Balcon','Billiard room':'Salle de billard','Music room':'Salle de musique','Music hall':'Salle de concert','Sitting room':'Petit salon',Pantry:'Garde-manger','Laundry room':'Buanderie','Train car':'Wagon',Platform:'Quai','Ticket hall':'Hall des billets',Cabin:'Cabine',Deck:'Pont','Engine room':'Salle des machines',Bridge:'Passerelle','Dining car':'Wagon-restaurant',Observatory:'Observatoire',Clinic:'Clinique','Emergency room':'Urgences',Ward:'Service',Morgue:'Morgue','Evidence room':'Salle des preuves','Interview room':'Salle d’interrogatoire','Police station':'Commissariat',Pier:'Jetée',Beach:'Plage',Forest:'Forêt',Cottage:'Cottage',Pavilion:'Pavillon',Courthouse:'Tribunal',Church:'Église',Monastery:'Monastère',Museum:'Musée','Exhibition hall':'Salle d’exposition',Gallery:'Galerie','Main hall':'Grande salle','Side hall':'Salle annexe','Private room':'Salon privé','Smoking room':'Salle fumeurs','Secret room':'Pièce secrète','Secret passage':'Passage secret','Wine cellar':'Cave à vin','Wine room':'Salle des vins','Tea room':'Salon de thé','Map room':'Salle des cartes','Clock tower':'Tour de l’horloge','West wing':'Aile ouest','East wing':'Aile est'},
    roles:{'Beside the delivery box':'Près du colis','Sitting in the chair':'Assise sur la chaise','Only person on the carpet':'Seule personne sur le tapis','A houseguest':'Invité','Beside the potted plant':'Près de la plante en pot','The victim':'La victime','Interior designer':'Décoratrice d’intérieur','Contractor':'Entrepreneur','Daughter':'Fille','Art dealer':'Marchand d’art','Groundskeeper':'Jardinier','Housekeeper':'Gouvernante','Nephew':'Neveu','Medium':'Médium','Physician':'Médecin','Neighbor':'Voisin','Curator':'Conservatrice','Guard':'Gardien','Artist':'Artiste','Collector':'Collectionneur','Conservator':'Restauratrice','Night clerk':'Réceptionniste de nuit','Truck driver':'Chauffeur routier','Sister':'Sœur','Mechanic':'Mécanicien','Traveler':'Voyageur','Lead actor':'Acteur principal','Director':'Réalisateur','Editor':'Monteur','Stunt double':'Cascadeur','Producer':'Producteur',Butler:'Majordome',Maid:'Femme de ménage',Detective:'Détective','Private detective':'Détective privé','Police officer':'Policier',Inspector:'Inspecteur',Doctor:'Médecin',Nurse:'Infirmière',Surgeon:'Chirurgien',Lawyer:'Avocat',Attorney:'Avocat',Judge:'Juge',Writer:'Écrivain',Novelist:'Romancier',Journalist:'Journaliste',Reporter:'Reporter',Photographer:'Photographe',Professor:'Professeur',Teacher:'Enseignant',Student:'Étudiant',Scientist:'Scientifique',Researcher:'Chercheur',Chef:'Chef cuisinier',Cook:'Cuisinier',Waiter:'Serveur',Waitress:'Serveuse',Bartender:'Barman',Pilot:'Pilote',Captain:'Capitaine',Sailor:'Marin',Engineer:'Ingénieur',Mechanic:'Mécanicien',Driver:'Chauffeur',Chauffeur:'Chauffeur',Actor:'Acteur',Actress:'Actrice',Singer:'Chanteur',Musician:'Musicien',Composer:'Compositeur',Dancer:'Danseur',Painter:'Peintre',Sculptor:'Sculpteur',Architect:'Architecte',Designer:'Designer','Business partner':'Associé',Businessman:'Homme d’affaires',Businesswoman:'Femme d’affaires',CEO:'PDG',Assistant:'Assistant',Secretary:'Secrétaire',Caretaker:'Gardien',Gardener:'Jardinier',Farmer:'Agriculteur',Rancher:'Éleveur',Banker:'Banquier',Accountant:'Comptable',Investor:'Investisseur',Heir:'Héritier',Heiress:'Héritière',Son:'Fils',Brother:'Frère',Mother:'Mère',Father:'Père',Wife:'Épouse',Husband:'Époux',Cousin:'Cousin',Uncle:'Oncle',Aunt:'Tante',Granddaughter:'Petite-fille',Grandson:'Petit-fils',Grandmother:'Grand-mère',Grandfather:'Grand-père',Friend:'Ami',Guest:'Invité',Houseguest:'Invité',Owner:'Propriétaire',Client:'Client',Customer:'Client','Security guard':'Agent de sécurité',Bodyguard:'Garde du corps',Valet:'Voiturier',Bellhop:'Bagagiste',Receptionist:'Réceptionniste',Librarian:'Bibliothécaire',Priest:'Prêtre',Pastor:'Pasteur',Nun:'Religieuse',Monk:'Moine','Fortune teller':'Voyant',Magician:'Magicien',Thief:'Voleur',Smuggler:'Contrebandier',Victim:'Victime'}
  },
  es: {
    settings:'Configuración',help:'Cómo jugar',close:'Cerrar',theme:'Apariencia',light:'Claro',dark:'Oscuro',toggle:'cambiar',clock:'Reloj',visible:'Visible',hidden:'Oculto',language:'Idioma',done:'Listo',gotIt:'Entendido',rules:'Las reglas del caso',preferences:'Preferencias',musicOn:'Reproducir música de fondo',musicOff:'Detener música de fondo',
    heroEyebrow:'Un juego de lógica y asesinato',heroOne:'Cada pista cuenta una historia.',heroTwo:'Cada historia termina en asesinato.',heroDescription:'Lee entre líneas. Encuentra al asesino. Caso cerrado.',investigation:'Tu investigación',caseFiles:'Casos',all:'Todos',veryEasy:'Muy fácil',easy:'Fácil',medium:'Medio',hard:'Difícil',expert:'Experto',release:'Fecha de estreno',difficulty:'Dificultad',title:'Título',recent:'Jugados recientemente',popular:'Populares',status:'Estado',caseNo:'CASO N.º',solved:'RESUELTO',revisit:'VOLVER AL CASO',open:'ABRIR CASO',viewAll:'VER TODOS LOS CASOS',copyright:'© Murdoku-inspired · independent fan project',collection:'Una colección original de misterios lógicos',howToPlayLink:'CÓMO JUGAR',back:'CASOS',row:'fila',column:'columna',suspects:'Sospechosos',suspectPrompt:'Toca una tarjeta y luego una casilla',evidence:'Las pruebas',clues:'PISTAS',markImpossible:'Marcar casilla imposible',clear:'Limpiar tablero',undo:'Deshacer',hint:'Pista',submit:'Comprobar',selectPerson:'Seleccionar a {name}',
    collectionStats:'Progreso de los casos', totalCases:'{count} casos', solvedCount:'{count} resueltos', progressCount:'{count} en curso', inProgress:'En curso', caseAvailable:'Caso disponible · abrir expediente', continueCase:'Continuar caso', solvedBoard:'Tablero resuelto', completedIn:'Resuelto en {time}', caseClosed:'CASO CERRADO', solvedHeadline:'La verdad queda en el expediente.', backToCases:'Volver a los casos', nextCase:'Caso siguiente', revisitCaseNamed:'Volver a {title}', openCaseNamed:'Abrir {title}',
    conflict:'Solo puede haber una persona por fila y columna. Mueve primero a quien entra en conflicto.',allCorrect:'Todas las ubicaciones son correctas.',incomplete:'Coloca a todos antes de comprobar.',solvedMessage:'Caso resuelto. {culprit} estuvo a solas con la víctima en {room}.',incorrect:'Aún no. Vuelve a leer las pruebas e inténtalo otra vez.',clueRowRoom:'{person} estaba en la fila {row}, en {room}.',clueColumn:'Estaba en la columna {column}.',clueColumnPair:'Estaba en las mismas dos columnas que {anchor}; nunca compartieron columna.',clueRole:'{role}.',clueVictim:'La víctima estaba a solas con el asesino en esa sala.',
    helpIntro:'Usa las pruebas para colocar a todos en la escena. Cada persona debe ocupar una fila y una columna distintas. Los muros delimitan las salas; la víctima comparte una sala con un solo sospechoso.',helpSelect:'Selecciona a un sospechoso y toca una casilla para colocarlo.',helpX:'Usa × para marcar una casilla imposible.',helpUndo:'Deshacer revierte el último movimiento. Pista revela una ubicación correcta.',helpSubmit:'Comprobar revisa todo el tablero e identifica al asesino.',
    rooms:{'Front hall':'Recibidor','Living room':'Sala de estar','Garden':'Jardín','Studio':'Estudio','Atrium':'Atrio','Courtyard':'Patio','Conservatory':'Invernadero','Chapel':'Capilla','Cellar':'Bodega','Vault':'Cámara acorazada','Main gallery':'Galería principal','Office':'Oficina','Room 12':'Habitación 12','Front desk':'Recepción','Parking lot':'Aparcamiento','Soundstage':'Plat ó de rodaje','Wardrobe':'Vestuario','Prop room':'Almacén de utilería',Kitchen:'Cocina','Dining room':'Comedor',Library:'Biblioteca',Ballroom:'Salón de baile',Study:'Despacho',Bedroom:'Dormitorio','Guest room':'Habitación de invitados',Basement:'Sótano',Attic:'Ático',Greenhouse:'Invernadero',Terrace:'Terraza',Pool:'Piscina',Garage:'Garaje',Workshop:'Taller',Foyer:'Vestíbulo',Theater:'Teatro',Theatre:'Teatro','Dressing room':'Camerino','Control room':'Sala de control',Lounge:'Sala de estar',Restaurant:'Restaurante',Bar:'Bar',Lobby:'Vestíbulo',Elevator:'Ascensor',Corridor:'Pasillo',Hallway:'Pasillo','Boiler room':'Sala de calderas',Roof:'Tejado',Rooftop:'Azotea',Dock:'Muelle',Warehouse:'Almacén',Archive:'Archivo',Archives:'Archivo',Laboratory:'Laboratorio',Lab:'Laboratorio','Garden shed':'Cobertizo del jardín',Veranda:'Porche',Balcony:'Balcón','Billiard room':'Sala de billar','Music room':'Sala de música','Music hall':'Sala de conciertos','Sitting room':'Salón',Pantry:'Despensa','Laundry room':'Lavandería','Train car':'Vagón',Platform:'Andén','Ticket hall':'Vestíbulo de billetes',Cabin:'Cabina',Deck:'Cubierta','Engine room':'Sala de máquinas',Bridge:'Puente','Dining car':'Coche comedor',Observatory:'Observatorio',Clinic:'Clínica','Emergency room':'Urgencias',Ward:'Sala','Morgue':'Morgue','Evidence room':'Sala de pruebas','Interview room':'Sala de interrogatorios','Police station':'Comisaría',Pier:'Embarcadero',Beach:'Playa',Forest:'Bosque',Cottage:'Cabaña',Pavilion:'Pabellón',Courthouse:'Juzgado',Church:'Iglesia',Monastery:'Monasterio',Museum:'Museo','Exhibition hall':'Sala de exposiciones',Gallery:'Galería','Main hall':'Sala principal','Side hall':'Sala lateral','Private room':'Sala privada','Smoking room':'Sala de fumadores','Secret room':'Sala secreta','Secret passage':'Pasadizo secreto','Wine cellar':'Bodega','Wine room':'Sala de vinos','Tea room':'Salón de té','Map room':'Sala de mapas','Clock tower':'Torre del reloj','West wing':'Ala oeste','East wing':'Ala este'},
    roles:{'Beside the delivery box':'Junto al paquete','Sitting in the chair':'Sentada en la silla','Only person on the carpet':'Única persona en la alfombra','A houseguest':'Invitado','Beside the potted plant':'Junto a la planta','The victim':'La víctima','Interior designer':'Diseñadora de interiores','Contractor':'Contratista','Daughter':'Hija','Art dealer':'Marchante de arte','Groundskeeper':'Jardinero','Housekeeper':'Ama de llaves','Nephew':'Sobrino','Medium':'Médium','Physician':'Médico','Neighbor':'Vecino','Curator':'Comisaria','Guard':'Guardia','Artist':'Artista','Collector':'Coleccionista','Conservator':'Restauradora','Night clerk':'Recepcionista nocturna','Truck driver':'Camionero','Sister':'Hermana','Mechanic':'Mecánico','Traveler':'Viajero','Lead actor':'Protagonista','Director':'Director','Editor':'Montador','Stunt double':'Especialista','Producer':'Productor',Butler:'Mayordomo',Maid:'Criada',Detective:'Detective','Private detective':'Detective privado','Police officer':'Agente de policía',Inspector:'Inspector',Doctor:'Médico',Nurse:'Enfermera',Surgeon:'Cirujano',Lawyer:'Abogado',Attorney:'Abogado',Judge:'Juez',Writer:'Escritor',Novelist:'Novelista',Journalist:'Periodista',Reporter:'Reportero',Photographer:'Fotógrafo',Professor:'Profesor',Teacher:'Docente',Student:'Estudiante',Scientist:'Científico',Researcher:'Investigador',Chef:'Chef',Cook:'Cocinero',Waiter:'Camarero',Waitress:'Camarera',Bartender:'Barman',Pilot:'Piloto',Captain:'Capitán',Sailor:'Marinero',Engineer:'Ingeniero',Mechanic:'Mecánico',Driver:'Conductor',Chauffeur:'Chófer',Actor:'Actor',Actress:'Actriz',Singer:'Cantante',Musician:'Músico',Composer:'Compositor',Dancer:'Bailarín',Painter:'Pintor',Sculptor:'Escultor',Architect:'Arquitecto',Designer:'Diseñador','Business partner':'Socio',Businessman:'Empresario',Businesswoman:'Empresaria',CEO:'Director ejecutivo',Assistant:'Asistente',Secretary:'Secretario',Caretaker:'Encargado',Gardener:'Jardinero',Farmer:'Granjero',Rancher:'Ganadero',Banker:'Banquero',Accountant:'Contable',Investor:'Inversor',Heir:'Heredero',Heiress:'Heredera',Son:'Hijo',Brother:'Hermano',Mother:'Madre',Father:'Padre',Wife:'Esposa',Husband:'Esposo',Cousin:'Primo',Uncle:'Tío',Aunt:'Tía',Granddaughter:'Nieta',Grandson:'Nieto',Grandmother:'Abuela',Grandfather:'Abuelo',Friend:'Amigo',Guest:'Invitado',Houseguest:'Invitado',Owner:'Propietario',Client:'Cliente',Customer:'Cliente','Security guard':'Guardia de seguridad',Bodyguard:'Guardaespaldas',Valet:'Aparcacoches',Bellhop:'Botones',Receptionist:'Recepcionista',Librarian:'Bibliotecario',Priest:'Sacerdote',Pastor:'Pastor',Nun:'Monja',Monk:'Monje','Fortune teller':'Adivino',Magician:'Mago',Thief:'Ladrón',Smuggler:'Contrabandista',Victim:'Víctima'}
  },
  ar: {
    settings:'الإعدادات',help:'طريقة اللعب',close:'إغلاق',theme:'المظهر',light:'فاتح',dark:'داكن',toggle:'تبديل',clock:'المؤقّت',visible:'ظاهر',hidden:'مخفي',language:'اللغة',done:'تم',gotIt:'فهمت',rules:'قواعد القضية',preferences:'التفضيلات',musicOn:'تشغيل موسيقى الخلفية',musicOff:'إيقاف موسيقى الخلفية',
    heroEyebrow:'لعبة منطق وجريمة',heroOne:'كل دليل يروي قصة.',heroTwo:'وكل قصة تنتهي بجريمة.',heroDescription:'اقرأ ما بين السطور. اعثر على القاتل. أُغلقت القضية.',investigation:'تحقيقك',caseFiles:'ملفات القضايا',all:'الكل',veryEasy:'سهل جدًا',easy:'سهل',medium:'متوسط',hard:'صعب',expert:'خبير',release:'تاريخ الإصدار',difficulty:'الصعوبة',title:'العنوان',recent:'لُعبت مؤخرًا',popular:'الأكثر رواجًا',status:'الحالة',caseNo:'القضية رقم',solved:'حُلّت',revisit:'إعادة فتح القضية',open:'افتح القضية',viewAll:'عرض كل القضايا',copyright:'© Murdoku-inspired · independent fan project',collection:'مجموعة أصلية من ألغاز المنطق',howToPlayLink:'طريقة اللعب',back:'القضايا',row:'الصف',column:'العمود',suspects:'المشتبه بهم',suspectPrompt:'اضغط على بطاقة للاختيار ثم على مربع',evidence:'الأدلة',clues:'أدلة',markImpossible:'ضع علامة على مربع مستحيل',clear:'مسح اللوحة',undo:'تراجع',hint:'تلميح',submit:'تحقّق',selectPerson:'اختر {name}',
    collectionStats:'تقدم ملفات القضايا', totalCases:'{count} قضية', solvedCount:'حُلّت {count}', progressCount:'قيد الحل: {count}', inProgress:'قيد الحل', caseAvailable:'القضية متاحة · افتح الملف', continueCase:'متابعة القضية', solvedBoard:'لوحة القضية المحلولة', completedIn:'حُلّت في {time}', caseClosed:'أُغلقت القضية', solvedHeadline:'الحقيقة محفوظة في الملف.', backToCases:'العودة إلى القضايا', nextCase:'القضية التالية', revisitCaseNamed:'إعادة فتح {title}', openCaseNamed:'افتح {title}',
    conflict:'شخص واحد في كل صف وعمود. حرّك الشخص المتعارض أولًا.',allCorrect:'كل المواقع صحيحة.',incomplete:'ضع الجميع قبل الإرسال.',solvedMessage:'حُلّت القضية. كان {culprit} وحده مع الضحية في {room}.',incorrect:'ليس بعد. أعد قراءة الأدلة وحاول مجددًا.',clueRowRoom:'كان {person} في الصف {row}، في {room}.',clueColumn:'كان في العمود {column}.',clueColumnPair:'كان في العمودين نفسيهما مع {anchor}، لكنهما لم يشغلا العمود نفسه.',clueRole:'{role}.',clueVictim:'كانت الضحية وحدها مع القاتل في تلك الغرفة.',
    helpIntro:'استخدم الأدلة لوضع الجميع في مسرح الجريمة. يجب أن يشغل كل شخص صفًا وعمودًا مختلفين. تحدد الجدران الغرف؛ وتتشارك الضحية غرفة مع مشتبه به واحد فقط.',helpSelect:'اختر مشتبهًا به ثم اضغط على مربع لوضعه.',helpX:'استخدم × لوضع علامة على مربع مستحيل.',helpUndo:'يلغي التراجع الحركة الأخيرة. يكشف التلميح موقعًا صحيحًا.',helpSubmit:'يتحقق الزر من اللوحة كاملة ويحدد القاتل.',
    rooms:{'Front hall':'الردهة الأمامية','Living room':'غرفة المعيشة','Garden':'الحديقة','Studio':'الاستوديو','Atrium':'الردهة','Courtyard':'الفناء','Conservatory':'البيت الزجاجي','Chapel':'الكنيسة الصغيرة','Cellar':'القبو','Vault':'الخزنة','Main gallery':'المعرض الرئيسي','Office':'المكتب','Room 12':'الغرفة 12','Front desk':'مكتب الاستقبال','Parking lot':'موقف السيارات','Soundstage':'استوديو التصوير','Wardrobe':'غرفة الملابس','Prop room':'مخزن الأدوات',Kitchen:'المطبخ','Dining room':'غرفة الطعام',Library:'المكتبة',Ballroom:'قاعة الرقص',Study:'غرفة الدراسة',Bedroom:'غرفة النوم','Guest room':'غرفة الضيوف',Basement:'الطابق السفلي',Attic:'العلّية',Greenhouse:'الدفيئة',Terrace:'الشرفة',Pool:'المسبح',Garage:'المرآب',Workshop:'الورشة',Foyer:'الردهة',Theater:'المسرح',Theatre:'المسرح','Dressing room':'غرفة تبديل الملابس','Control room':'غرفة التحكم',Lounge:'الاستراحة',Restaurant:'المطعم',Bar:'الحانة',Lobby:'البهو',Elevator:'المصعد',Corridor:'الممر',Hallway:'الرواق','Boiler room':'غرفة الغلاية',Roof:'السطح',Rooftop:'سطح المبنى',Dock:'الرصيف',Warehouse:'المستودع',Archive:'الأرشيف',Archives:'الأرشيف',Laboratory:'المختبر',Lab:'المختبر','Garden shed':'كوخ الحديقة',Veranda:'الشرفة',Balcony:'الشرفة','Billiard room':'غرفة البلياردو','Music room':'غرفة الموسيقى','Music hall':'قاعة الموسيقى','Sitting room':'غرفة الجلوس',Pantry:'المخزن','Laundry room':'غرفة الغسيل','Train car':'عربة القطار',Platform:'الرصيف','Ticket hall':'قاعة التذاكر',Cabin:'المقصورة',Deck:'السطح','Engine room':'غرفة المحرك',Bridge:'الجسر','Dining car':'عربة الطعام',Observatory:'المرصد',Clinic:'العيادة','Emergency room':'الطوارئ',Ward:'الجناح',Morgue:'المشرحة','Evidence room':'غرفة الأدلة','Interview room':'غرفة الاستجواب','Police station':'مركز الشرطة',Pier:'الرصيف',Beach:'الشاطئ',Forest:'الغابة',Cottage:'الكوخ',Pavilion:'الجناح',Courthouse:'المحكمة',Church:'الكنيسة',Monastery:'الدير',Museum:'المتحف','Exhibition hall':'قاعة المعرض',Gallery:'المعرض','Main hall':'القاعة الرئيسية','Side hall':'القاعة الجانبية','Private room':'الغرفة الخاصة','Smoking room':'غرفة التدخين','Secret room':'الغرفة السرية','Secret passage':'الممر السري','Wine cellar':'قبو النبيذ','Wine room':'غرفة النبيذ','Tea room':'غرفة الشاي','Map room':'غرفة الخرائط','Clock tower':'برج الساعة','West wing':'الجناح الغربي','East wing':'الجناح الشرقي'},
    roles:{'Beside the delivery box':'بجانب صندوق التوصيل','Sitting in the chair':'جالسة على الكرسي','Only person on the carpet':'الشخص الوحيد على السجادة','A houseguest':'ضيف في المنزل','Beside the potted plant':'بجانب النبتة','The victim':'الضحية','Interior designer':'مصمم داخلي','Contractor':'مقاول','Daughter':'ابنة','Art dealer':'تاجر فنون','Groundskeeper':'بستاني','Housekeeper':'مدبرة منزل','Nephew':'ابن الأخ','Medium':'وسيط روحي','Physician':'طبيب','Neighbor':'جار','Curator':'قيّم فني','Guard':'حارس','Artist':'فنان','Collector':'جامع مقتنيات','Conservator':'مرمم','Night clerk':'موظف استقبال ليلي','Truck driver':'سائق شاحنة','Sister':'أخت','Mechanic':'ميكانيكي','Traveler':'مسافر','Lead actor':'ممثل رئيسي','Director':'مخرج','Editor':'محرر','Stunt double':'بديل ممثل','Producer':'منتج',Butler:'خادم',Maid:'خادمة',Detective:'محقق','Private detective':'محقق خاص','Police officer':'ضابط شرطة',Inspector:'مفتش',Doctor:'طبيب',Nurse:'ممرضة',Surgeon:'جرّاح',Lawyer:'محامٍ',Attorney:'محامٍ',Judge:'قاضٍ',Writer:'كاتب',Novelist:'روائي',Journalist:'صحفي',Reporter:'مراسل',Photographer:'مصور',Professor:'أستاذ',Teacher:'معلم',Student:'طالب',Scientist:'عالِم',Researcher:'باحث',Chef:'طاهٍ',Cook:'طباخ',Waiter:'نادل',Waitress:'نادلة',Bartender:'ساقي',Pilot:'طيار',Captain:'قبطان',Sailor:'بحار',Engineer:'مهندس',Driver:'سائق',Chauffeur:'سائق خاص',Actor:'ممثل',Actress:'ممثلة',Singer:'مغنٍ',Musician:'موسيقي',Composer:'ملحن',Dancer:'راقص',Painter:'رسام',Sculptor:'نحات',Architect:'مهندس معماري',Designer:'مصمم','Business partner':'شريك عمل',Businessman:'رجل أعمال',Businesswoman:'سيدة أعمال',CEO:'مدير تنفيذي',Assistant:'مساعد',Secretary:'سكرتير',Caretaker:'قيّم',Gardener:'بستاني',Farmer:'مزارع',Rancher:'مربّي ماشية',Banker:'مصرفي',Accountant:'محاسب',Investor:'مستثمر',Heir:'وارث',Heiress:'وارثة',Son:'ابن',Brother:'أخ',Mother:'أم',Father:'أب',Wife:'زوجة',Husband:'زوج',Cousin:'ابن العم',Uncle:'عم',Aunt:'عمة',Granddaughter:'حفيدة',Grandson:'حفيد',Grandmother:'جدة',Grandfather:'جد',Friend:'صديق',Guest:'ضيف',Houseguest:'ضيف في المنزل',Owner:'مالك',Client:'عميل',Customer:'زبون','Security guard':'حارس أمن',Bodyguard:'حارس شخصي',Valet:'عامل صف السيارات',Bellhop:'حمّال',Receptionist:'موظف استقبال',Librarian:'أمين مكتبة',Priest:'قسيس',Pastor:'راعي كنيسة',Nun:'راهبة',Monk:'راهب','Fortune teller':'عرّاف',Magician:'ساحر',Thief:'لص',Smuggler:'مهرّب',Victim:'ضحية'}
  },
  ru: {
    settings:'Настройки',help:'Как играть',close:'Закрыть',theme:'Оформление',light:'Светлая',dark:'Тёмная',toggle:'переключить',clock:'Таймер',visible:'Показан',hidden:'Скрыт',language:'Язык',done:'Готово',gotIt:'Понятно',rules:'Правила дела',preferences:'Параметры',musicOn:'Включить фоновую музыку',musicOff:'Выключить фоновую музыку',
    heroEyebrow:'Игра в логику и убийство',heroOne:'Каждая улика рассказывает историю.',heroTwo:'Каждая история заканчивается убийством.',heroDescription:'Читайте между строк. Найдите убийцу. Дело закрыто.',investigation:'Ваше расследование',caseFiles:'Дела',all:'Все',veryEasy:'Очень легко',easy:'Легко',medium:'Средне',hard:'Сложно',expert:'Эксперт',release:'Дата выхода',difficulty:'Сложность',title:'Название',recent:'Недавно сыгранные',popular:'Популярные',status:'Статус',caseNo:'ДЕЛО №',solved:'РАСКРЫТО',revisit:'ОТКРЫТЬ ДЕЛО СНОВА',open:'ОТКРЫТЬ ДЕЛО',viewAll:'ПОКАЗАТЬ ВСЕ ДЕЛА',copyright:'© Murdoku-inspired · independent fan project',collection:'Оригинальная коллекция логических загадок',howToPlayLink:'КАК ИГРАТЬ',back:'ДЕЛА',row:'ряд',column:'столбец',suspects:'Подозреваемые',suspectPrompt:'Выберите карточку, затем нажмите на клетку',evidence:'Улики',clues:'УЛИК',markImpossible:'Отметить невозможную клетку',clear:'Очистить поле',undo:'Отменить',hint:'Подсказка',submit:'Проверить',selectPerson:'Выбрать: {name}',
    collectionStats:'Прогресс по делам', totalCases:'Дел: {count}', solvedCount:'Решено: {count}', progressCount:'В работе: {count}', inProgress:'В работе', caseAvailable:'Дело доступно · открыть папку', continueCase:'Продолжить дело', solvedBoard:'Решённая схема дела', completedIn:'Решено за {time}', caseClosed:'ДЕЛО ЗАКРЫТО', solvedHeadline:'Ответ сохранён в деле.', backToCases:'К списку дел', nextCase:'Следующее дело', revisitCaseNamed:'Открыть снова: {title}', openCaseNamed:'Открыть: {title}',
    conflict:'В каждом ряду и столбце может быть только один человек. Сначала переместите того, кто мешает.',allCorrect:'Все позиции указаны верно.',incomplete:'Перед отправкой разместите всех.',solvedMessage:'Дело раскрыто. {culprit} остался наедине с жертвой в помещении «{room}».',incorrect:'Пока нет. Перечитайте улики и попробуйте ещё раз.',clueRowRoom:'{person} находился в ряду {row}, в помещении «{room}».',clueColumn:'Он находился в столбце {column}.',clueColumnPair:'Он находился в тех же двух столбцах, что и {anchor}; один столбец они не делили.',clueRole:'{role}.',clueVictim:'Жертва оставалась в этой комнате наедине с убийцей.',
    helpIntro:'Используйте улики, чтобы разместить всех на плане. Каждый человек должен занять отдельные ряд и столбец. Толстые стены очерчивают комнаты; жертва делит комнату ровно с одним подозреваемым.',helpSelect:'Выберите подозреваемого, затем нажмите на клетку.',helpX:'Знаком × отметьте клетку, которая не подходит.',helpUndo:'Отмена возвращает последний ход. Подсказка показывает верное место.',helpSubmit:'Проверка сверяет всё поле и указывает убийцу.',
    rooms:{'Front hall':'Прихожая','Living room':'Гостиная','Garden':'Сад','Studio':'Студия','Atrium':'Атриум','Courtyard':'Внутренний двор','Conservatory':'Оранжерея','Chapel':'Часовня','Cellar':'Подвал','Vault':'Хранилище','Main gallery':'Главная галерея','Office':'Кабинет','Room 12':'Комната 12','Front desk':'Стойка регистрации','Parking lot':'Парковка','Soundstage':'Съёмочная площадка','Wardrobe':'Гримёрная','Prop room':'Кладовая реквизита',Kitchen:'Кухня','Dining room':'Столовая',Library:'Библиотека',Ballroom:'Бальный зал',Study:'Кабинет',Bedroom:'Спальня','Guest room':'Гостевая комната',Basement:'Подвал',Attic:'Чердак',Greenhouse:'Теплица',Terrace:'Терраса',Pool:'Бассейн',Garage:'Гараж',Workshop:'Мастерская',Foyer:'Вестибюль',Theater:'Театр',Theatre:'Театр','Dressing room':'Гримёрная','Control room':'Аппаратная',Lounge:'Зал отдыха',Restaurant:'Ресторан',Bar:'Бар',Lobby:'Холл',Elevator:'Лифт',Corridor:'Коридор',Hallway:'Коридор','Boiler room':'Котельная',Roof:'Крыша',Rooftop:'Крыша',Dock:'Причал',Warehouse:'Склад',Archive:'Архив',Archives:'Архив',Laboratory:'Лаборатория',Lab:'Лаборатория','Garden shed':'Садовый домик',Veranda:'Веранда',Balcony:'Балкон','Billiard room':'Бильярдная','Music room':'Музыкальная комната','Music hall':'Концертный зал','Sitting room':'Гостиная',Pantry:'Кладовая','Laundry room':'Прачечная','Train car':'Вагон',Platform:'Платформа','Ticket hall':'Зал ожидания',Cabin:'Каюта',Deck:'Палуба','Engine room':'Машинное отделение',Bridge:'Мостик','Dining car':'Вагон-ресторан',Observatory:'Обсерватория',Clinic:'Клиника','Emergency room':'Приёмное отделение',Ward:'Палата',Morgue:'Морг','Evidence room':'Комната улик','Interview room':'Комната допросов','Police station':'Полицейский участок',Pier:'Пирс',Beach:'Пляж',Forest:'Лес',Cottage:'Коттедж',Pavilion:'Павильон',Courthouse:'Здание суда',Church:'Церковь',Monastery:'Монастырь',Museum:'Музей','Exhibition hall':'Выставочный зал',Gallery:'Галерея','Main hall':'Главный зал','Side hall':'Боковой зал','Private room':'Личная комната','Smoking room':'Комната для курения','Secret room':'Тайная комната','Secret passage':'Тайный проход','Wine cellar':'Винный погреб','Wine room':'Винная комната','Tea room':'Чайная','Map room':'Картографический зал','Clock tower':'Часовая башня','West wing':'Западное крыло','East wing':'Восточное крыло'},
    roles:{'Beside the delivery box':'Рядом с посылкой','Sitting in the chair':'Сидела в кресле','Only person on the carpet':'Единственный человек на ковре','A houseguest':'Гость дома','Beside the potted plant':'Рядом с растением в горшке','The victim':'Жертва','Interior designer':'Дизайнер интерьеров','Contractor':'Подрядчик','Daughter':'Дочь','Art dealer':'Арт-дилер','Groundskeeper':'Садовник','Housekeeper':'Экономка','Nephew':'Племянник','Medium':'Медиум','Physician':'Врач','Neighbor':'Сосед','Curator':'Куратор','Guard':'Охранник','Artist':'Художник','Collector':'Коллекционер','Conservator':'Реставратор','Night clerk':'Ночной администратор','Truck driver':'Дальнобойщик','Sister':'Сестра','Mechanic':'Механик','Traveler':'Путешественник','Lead actor':'Исполнитель главной роли','Director':'Режиссёр','Editor':'Монтажёр','Stunt double':'Каскадёр','Producer':'Продюсер',Butler:'Дворецкий',Maid:'Горничная',Detective:'Детектив','Private detective':'Частный детектив','Police officer':'Полицейский',Inspector:'Инспектор',Doctor:'Врач',Nurse:'Медсестра',Surgeon:'Хирург',Lawyer:'Юрист',Attorney:'Адвокат',Judge:'Судья',Writer:'Писатель',Novelist:'Романист',Journalist:'Журналист',Reporter:'Репортёр',Photographer:'Фотограф',Professor:'Профессор',Teacher:'Учитель',Student:'Студент',Scientist:'Учёный',Researcher:'Исследователь',Chef:'Шеф-повар',Cook:'Повар',Waiter:'Официант',Waitress:'Официантка',Bartender:'Бармен',Pilot:'Пилот',Captain:'Капитан',Sailor:'Моряк',Engineer:'Инженер',Driver:'Водитель',Chauffeur:'Шофёр',Actor:'Актёр',Actress:'Актриса',Singer:'Певец',Musician:'Музыкант',Composer:'Композитор',Dancer:'Танцор',Painter:'Художник',Sculptor:'Скульптор',Architect:'Архитектор',Designer:'Дизайнер','Business partner':'Деловой партнёр',Businessman:'Бизнесмен',Businesswoman:'Бизнесвумен',CEO:'Генеральный директор',Assistant:'Ассистент',Secretary:'Секретарь',Caretaker:'Смотритель',Gardener:'Садовник',Farmer:'Фермер',Rancher:'Скотовод',Banker:'Банкир',Accountant:'Бухгалтер',Investor:'Инвестор',Heir:'Наследник',Heiress:'Наследница',Son:'Сын',Brother:'Брат',Mother:'Мать',Father:'Отец',Wife:'Жена',Husband:'Муж',Cousin:'Двоюродный брат',Uncle:'Дядя',Aunt:'Тётя',Granddaughter:'Внучка',Grandson:'Внук',Grandmother:'Бабушка',Grandfather:'Дедушка',Friend:'Друг',Guest:'Гость',Houseguest:'Гость дома',Owner:'Владелец',Client:'Клиент',Customer:'Покупатель','Security guard':'Охранник',Bodyguard:'Телохранитель',Valet:'Парковщик',Bellhop:'Носильщик',Receptionist:'Администратор',Librarian:'Библиотекарь',Priest:'Священник',Pastor:'Пастор',Nun:'Монахиня',Monk:'Монах','Fortune teller':'Гадалка',Magician:'Фокусник',Thief:'Вор',Smuggler:'Контрабандист',Victim:'Жертва'}
  },
  'zh-CN': {
    settings:'设置',help:'玩法说明',close:'关闭',theme:'外观',light:'浅色',dark:'深色',toggle:'切换',clock:'计时器',visible:'显示',hidden:'隐藏',language:'语言',done:'完成',gotIt:'知道了',rules:'案件规则',preferences:'偏好设置',musicOn:'播放背景音乐',musicOff:'停止背景音乐',
    heroEyebrow:'逻辑与谋杀游戏',heroOne:'每条线索都讲述一个故事。',heroTwo:'每个故事都以谋杀告终。',heroDescription:'从字里行间寻找真相，找出凶手，结案。',investigation:'你的调查',caseFiles:'案件档案',all:'全部',veryEasy:'非常简单',easy:'简单',medium:'中等',hard:'困难',expert:'专家',release:'发布日期',difficulty:'难度',title:'标题',recent:'最近游玩',popular:'热门',status:'状态',caseNo:'案件编号',solved:'已破解',revisit:'重玩案件',open:'打开案件',viewAll:'查看全部案件',copyright:'© Murdoku-inspired · independent fan project',collection:'原创逻辑谜案合集',howToPlayLink:'玩法说明',back:'案件',row:'行',column:'列',suspects:'嫌疑人',suspectPrompt:'点击卡片选择人物，再点击方格放置',evidence:'证据',clues:'条线索',markImpossible:'标记不可能的位置',clear:'清空棋盘',undo:'撤销',hint:'提示',submit:'提交',selectPerson:'选择{name}',
    collectionStats:'案件进度', totalCases:'共{count}个案件', solvedCount:'已破解{count}个', progressCount:'进行中{count}个', inProgress:'调查中', caseAvailable:'案件可查 · 打开档案', continueCase:'继续调查', solvedBoard:'已破解案件网格', completedIn:'用时{time}', caseClosed:'案件已结案', solvedHeadline:'真相已归档。', backToCases:'返回案件列表', nextCase:'下一个案件', revisitCaseNamed:'重访：{title}', openCaseNamed:'打开：{title}',
    conflict:'每行和每列只能放一人。请先移动冲突的人物。',allCorrect:'所有位置都正确。',incomplete:'提交前请放置所有人物。',solvedMessage:'案件已破解。{culprit}曾在{room}与受害者独处。',incorrect:'还不对。重新阅读证据再试一次。',clueRowRoom:'{person}位于第{row}行的{room}。',clueColumn:'此人在第{column}列。',clueColumnPair:'此人与{anchor}位于相同的两列范围内，但两人不在同一列。',clueRole:'{role}。',clueVictim:'受害者曾在该房间与凶手独处。',
    helpIntro:'根据证据，将所有人放置在案发现场。每个人必须占据不同的行和列。粗墙线勾勒出各个房间；受害者所在房间恰好还有一名嫌疑人。',helpSelect:'选择一名嫌疑人，再点击方格放置。',helpX:'使用×标记不可能的位置。',helpUndo:'撤销上一步操作。提示会显示一个正确位置。',helpSubmit:'提交后会检查整个棋盘并指出凶手。',
    rooms:{'Front hall':'门厅','Living room':'客厅','Garden':'花园','Studio':'工作室','Atrium':'中庭','Courtyard':'庭院','Conservatory':'温室','Chapel':'小教堂','Cellar':'地窖','Vault':'金库','Main gallery':'主展厅','Office':'办公室','Room 12':'12号房','Front desk':'前台','Parking lot':'停车场','Soundstage':'摄影棚','Wardrobe':'服装间','Prop room':'道具间',Kitchen:'厨房','Dining room':'餐厅',Library:'图书馆',Ballroom:'舞厅',Study:'书房',Bedroom:'卧室','Guest room':'客房',Basement:'地下室',Attic:'阁楼',Greenhouse:'温室',Terrace:'露台',Pool:'泳池',Garage:'车库',Workshop:'工坊',Foyer:'门厅',Theater:'剧院',Theatre:'剧院','Dressing room':'更衣室','Control room':'控制室',Lounge:'休息室',Restaurant:'餐馆',Bar:'酒吧',Lobby:'大厅',Elevator:'电梯',Corridor:'走廊',Hallway:'走廊','Boiler room':'锅炉房',Roof:'屋顶',Rooftop:'屋顶',Dock:'码头',Warehouse:'仓库',Archive:'档案室',Archives:'档案室',Laboratory:'实验室',Lab:'实验室','Garden shed':'园艺棚',Veranda:'门廊',Balcony:'阳台','Billiard room':'台球室','Music room':'音乐室','Music hall':'音乐厅','Sitting room':'起居室',Pantry:'食品储藏室','Laundry room':'洗衣房','Train car':'车厢',Platform:'站台','Ticket hall':'售票大厅',Cabin:'船舱',Deck:'甲板','Engine room':'机舱',Bridge:'驾驶台','Dining car':'餐车',Observatory:'天文台',Clinic:'诊所','Emergency room':'急诊室',Ward:'病房',Morgue:'停尸房','Evidence room':'证物室','Interview room':'审讯室','Police station':'警察局',Pier:'栈桥',Beach:'海滩',Forest:'森林',Cottage:'小屋',Pavilion:'亭子',Courthouse:'法院',Church:'教堂',Monastery:'修道院',Museum:'博物馆','Exhibition hall':'展览厅',Gallery:'画廊','Main hall':'主厅','Side hall':'侧厅','Private room':'包间','Smoking room':'吸烟室','Secret room':'密室','Secret passage':'密道','Wine cellar':'酒窖','Wine room':'酒室','Tea room':'茶室','Map room':'地图室','Clock tower':'钟楼','West wing':'西翼','East wing':'东翼'},
    roles:{'Beside the delivery box':'在快递箱旁','Sitting in the chair':'坐在椅子上','Only person on the carpet':'地毯上唯一的人','A houseguest':'家庭客人','Beside the potted plant':'在盆栽旁','The victim':'受害者','Interior designer':'室内设计师','Contractor':'承包商','Daughter':'女儿','Art dealer':'艺术品经纪人','Groundskeeper':'园丁','Housekeeper':'管家','Nephew':'侄子','Medium':'灵媒','Physician':'医生','Neighbor':'邻居','Curator':'策展人','Guard':'守卫','Artist':'艺术家','Collector':'收藏家','Conservator':'文物修复师','Night clerk':'夜班接待员','Truck driver':'卡车司机','Sister':'姐妹','Mechanic':'机械师','Traveler':'旅客','Lead actor':'主演','Director':'导演','Editor':'剪辑师','Stunt double':'特技替身','Producer':'制片人',Butler:'男管家',Maid:'女佣',Detective:'侦探','Private detective':'私家侦探','Police officer':'警察',Inspector:'督察',Doctor:'医生',Nurse:'护士',Surgeon:'外科医生',Lawyer:'律师',Attorney:'律师',Judge:'法官',Writer:'作家',Novelist:'小说家',Journalist:'记者',Reporter:'记者',Photographer:'摄影师',Professor:'教授',Teacher:'教师',Student:'学生',Scientist:'科学家',Researcher:'研究员',Chef:'主厨',Cook:'厨师',Waiter:'服务员',Waitress:'服务员',Bartender:'调酒师',Pilot:'飞行员',Captain:'船长',Sailor:'水手',Engineer:'工程师',Driver:'司机',Chauffeur:'专职司机',Actor:'演员',Actress:'女演员',Singer:'歌手',Musician:'音乐家',Composer:'作曲家',Dancer:'舞者',Painter:'画家',Sculptor:'雕塑家',Architect:'建筑师',Designer:'设计师','Business partner':'商业伙伴',Businessman:'商人',Businesswoman:'女商人',CEO:'首席执行官',Assistant:'助理',Secretary:'秘书',Caretaker:'看护人',Gardener:'园丁',Farmer:'农民',Rancher:'牧场主',Banker:'银行家',Accountant:'会计',Investor:'投资人',Heir:'继承人',Heiress:'女继承人',Son:'儿子',Brother:'兄弟',Mother:'母亲',Father:'父亲',Wife:'妻子',Husband:'丈夫',Cousin:'表亲',Uncle:'叔叔',Aunt:'阿姨',Granddaughter:'孙女',Grandson:'孙子',Grandmother:'祖母',Grandfather:'祖父',Friend:'朋友',Guest:'客人',Houseguest:'家庭客人',Owner:'所有者',Client:'客户',Customer:'顾客','Security guard':'保安',Bodyguard:'保镖',Valet:'代客泊车员',Bellhop:'行李员',Receptionist:'接待员',Librarian:'图书管理员',Priest:'牧师',Pastor:'牧师',Nun:'修女',Monk:'僧侣','Fortune teller':'算命师',Magician:'魔术师',Thief:'小偷',Smuggler:'走私犯',Victim:'受害者'}
  },
  'zh-TW': {
    settings:'設定',help:'遊戲說明',close:'關閉',theme:'外觀',light:'淺色',dark:'深色',toggle:'切換',clock:'計時器',visible:'顯示',hidden:'隱藏',language:'語言',done:'完成',gotIt:'知道了',rules:'案件規則',preferences:'偏好設定',musicOn:'播放背景音樂',musicOff:'停止背景音樂',
    heroEyebrow:'邏輯與謀殺遊戲',heroOne:'每條線索都訴說一個故事。',heroTwo:'每個故事都以謀殺告終。',heroDescription:'從字裡行間尋找真相，找出兇手，結案。',investigation:'你的調查',caseFiles:'案件檔案',all:'全部',veryEasy:'非常簡單',easy:'簡單',medium:'中等',hard:'困難',expert:'專家',release:'發佈日期',difficulty:'難度',title:'標題',recent:'最近遊玩',popular:'熱門',status:'狀態',caseNo:'案件編號',solved:'已破解',revisit:'重玩案件',open:'開啟案件',viewAll:'查看所有案件',copyright:'© Murdoku-inspired · independent fan project',collection:'原創邏輯謎案合集',howToPlayLink:'遊戲說明',back:'案件',row:'列',column:'欄',suspects:'嫌疑人',suspectPrompt:'點選卡片選擇人物，再點選方格放置',evidence:'證據',clues:'條線索',markImpossible:'標記不可能的位置',clear:'清空棋盤',undo:'復原',hint:'提示',submit:'提交',selectPerson:'選擇{name}',
    collectionStats:'案件進度', totalCases:'共{count}個案件', solvedCount:'已破解{count}個', progressCount:'進行中{count}個', inProgress:'調查中', caseAvailable:'案件可查 · 開啟檔案', continueCase:'繼續調查', solvedBoard:'已破解案件網格', completedIn:'用時{time}', caseClosed:'案件已結案', solvedHeadline:'真相已歸檔。', backToCases:'返回案件列表', nextCase:'下一個案件', revisitCaseNamed:'重訪：{title}', openCaseNamed:'開啟：{title}',
    conflict:'每列和每欄只能放一人。請先移動衝突的人物。',allCorrect:'所有位置都正確。',incomplete:'提交前請放置所有人物。',solvedMessage:'案件已破解。{culprit}曾在{room}與被害者獨處。',incorrect:'還不對。重新閱讀證據再試一次。',clueRowRoom:'{person}位於第{row}列的{room}。',clueColumn:'此人在第{column}欄。',clueColumnPair:'此人與{anchor}位於相同的兩欄範圍內，但兩人不在同一欄。',clueRole:'{role}。',clueVictim:'被害者曾在該房間與兇手獨處。',
    helpIntro:'根據證據，將所有人放置在案發現場。每個人必須佔據不同的列和欄。粗牆線勾勒出各個房間；被害者所在房間恰好還有一名嫌疑人。',helpSelect:'選擇一名嫌疑人，再點選方格放置。',helpX:'使用×標記不可能的位置。',helpUndo:'復原上一步操作。提示會顯示一個正確位置。',helpSubmit:'提交後會檢查整個棋盤並指出兇手。',
    rooms:{'Front hall':'門廳','Living room':'客廳','Garden':'花園','Studio':'工作室','Atrium':'中庭','Courtyard':'庭院','Conservatory':'溫室','Chapel':'小教堂','Cellar':'地窖','Vault':'金庫','Main gallery':'主展廳','Office':'辦公室','Room 12':'12號房','Front desk':'櫃檯','Parking lot':'停車場','Soundstage':'攝影棚','Wardrobe':'服裝間','Prop room':'道具間',Kitchen:'廚房','Dining room':'餐廳',Library:'圖書館',Ballroom:'舞廳',Study:'書房',Bedroom:'臥室','Guest room':'客房',Basement:'地下室',Attic:'閣樓',Greenhouse:'溫室',Terrace:'露台',Pool:'泳池',Garage:'車庫',Workshop:'工坊',Foyer:'門廳',Theater:'劇院',Theatre:'劇院','Dressing room':'更衣室','Control room':'控制室',Lounge:'休息室',Restaurant:'餐館',Bar:'酒吧',Lobby:'大廳',Elevator:'電梯',Corridor:'走廊',Hallway:'走廊','Boiler room':'鍋爐房',Roof:'屋頂',Rooftop:'屋頂',Dock:'碼頭',Warehouse:'倉庫',Archive:'檔案室',Archives:'檔案室',Laboratory:'實驗室',Lab:'實驗室','Garden shed':'園藝棚',Veranda:'門廊',Balcony:'陽台','Billiard room':'撞球室','Music room':'音樂室','Music hall':'音樂廳','Sitting room':'起居室',Pantry:'食品儲藏室','Laundry room':'洗衣房','Train car':'車廂',Platform:'月台','Ticket hall':'售票大廳',Cabin:'船艙',Deck:'甲板','Engine room':'機艙',Bridge:'駕駛台','Dining car':'餐車',Observatory:'天文台',Clinic:'診所','Emergency room':'急診室',Ward:'病房',Morgue:'停屍間','Evidence room':'證物室','Interview room':'偵訊室','Police station':'警察局',Pier:'棧橋',Beach:'海灘',Forest:'森林',Cottage:'小屋',Pavilion:'亭子',Courthouse:'法院',Church:'教堂',Monastery:'修道院',Museum:'博物館','Exhibition hall':'展覽廳',Gallery:'畫廊','Main hall':'主廳','Side hall':'側廳','Private room':'包廂','Smoking room':'吸菸室','Secret room':'密室','Secret passage':'密道','Wine cellar':'酒窖','Wine room':'酒室','Tea room':'茶室','Map room':'地圖室','Clock tower':'鐘樓','West wing':'西翼','East wing':'東翼'},
    roles:{'Beside the delivery box':'在快遞箱旁','Sitting in the chair':'坐在椅子上','Only person on the carpet':'地毯上唯一的人','A houseguest':'家庭客人','Beside the potted plant':'在盆栽旁','The victim':'被害者','Interior designer':'室內設計師','Contractor':'承包商','Daughter':'女兒','Art dealer':'藝術品經紀人','Groundskeeper':'園丁','Housekeeper':'管家','Nephew':'姪子','Medium':'靈媒','Physician':'醫生','Neighbor':'鄰居','Curator':'策展人','Guard':'守衛','Artist':'藝術家','Collector':'收藏家','Conservator':'文物修復師','Night clerk':'大夜接待員','Truck driver':'卡車司機','Sister':'姊妹','Mechanic':'機械師','Traveler':'旅客','Lead actor':'主演','Director':'導演','Editor':'剪輯師','Stunt double':'特技替身','Producer':'製片人',Butler:'男管家',Maid:'女傭',Detective:'偵探','Private detective':'私家偵探','Police officer':'警察',Inspector:'督察',Doctor:'醫生',Nurse:'護理師',Surgeon:'外科醫生',Lawyer:'律師',Attorney:'律師',Judge:'法官',Writer:'作家',Novelist:'小說家',Journalist:'記者',Reporter:'記者',Photographer:'攝影師',Professor:'教授',Teacher:'教師',Student:'學生',Scientist:'科學家',Researcher:'研究員',Chef:'主廚',Cook:'廚師',Waiter:'服務生',Waitress:'服務生',Bartender:'調酒師',Pilot:'飛行員',Captain:'船長',Sailor:'水手',Engineer:'工程師',Driver:'司機',Chauffeur:'專職司機',Actor:'演員',Actress:'女演員',Singer:'歌手',Musician:'音樂家',Composer:'作曲家',Dancer:'舞者',Painter:'畫家',Sculptor:'雕塑家',Architect:'建築師',Designer:'設計師','Business partner':'商業夥伴',Businessman:'商人',Businesswoman:'女商人',CEO:'執行長',Assistant:'助理',Secretary:'秘書',Caretaker:'看護人',Gardener:'園丁',Farmer:'農夫',Rancher:'牧場主',Banker:'銀行家',Accountant:'會計',Investor:'投資人',Heir:'繼承人',Heiress:'女繼承人',Son:'兒子',Brother:'兄弟',Mother:'母親',Father:'父親',Wife:'妻子',Husband:'丈夫',Cousin:'表親',Uncle:'叔叔',Aunt:'阿姨',Granddaughter:'孫女',Grandson:'孫子',Grandmother:'祖母',Grandfather:'祖父',Friend:'朋友',Guest:'客人',Houseguest:'家庭客人',Owner:'所有人',Client:'客戶',Customer:'顧客','Security guard':'保全',Bodyguard:'保鑣',Valet:'代客泊車員',Bellhop:'行李員',Receptionist:'接待員',Librarian:'圖書館員',Priest:'牧師',Pastor:'牧師',Nun:'修女',Monk:'僧侶','Fortune teller':'算命師',Magician:'魔術師',Thief:'小偷',Smuggler:'走私犯',Victim:'被害者'}
  },
};

const commonCaseCopy = {
  en: {},
  fr: {
    'c01': { title:'Livraison 24 h/24', desc:'Une livraison est arrivée. Un invité n’est jamais reparti.', place:'LE SAULE ET LE VIN' },
    'c02': { title:'Mort sur plan', desc:'L’architecte connaissait chaque issue.', place:'MAISON MORROW' },
    'c03': { title:'Une nuit tranquille', desc:'Une tempête. Six invités. Aucun témoin.', place:'MANOIR BLACKTHORN' },
    'c04': { title:'La muse disparue', desc:'Un chef-d’œuvre a disparu avant le meurtre.', place:'GALERIE DORÉE' },
    'c05': { title:'Minuit au motel', desc:'La chambre 12 était fermée de l’intérieur.', place:'MOTEL STARLIGHT' },
    'c06': { title:'Le dernier plan', desc:'Le réalisateur disait que c’était la fin parfaite.', place:'STUDIOS SILVER SCREEN' },
  },
  es: {
    'c01': { title:'Entrega 24 horas', desc:'Llegó un paquete. Un invitado nunca se marchó.', place:'EL SAUCE Y EL VINO' },
    'c02': { title:'Muerte por diseño', desc:'El arquitecto conocía todas las salidas.', place:'CASA MORROW' },
    'c03': { title:'Una noche tranquila', desc:'Una tormenta. Seis invitados. Ningún testigo.', place:'MANSIÓN BLACKTHORN' },
    'c04': { title:'La musa desaparecida', desc:'Una obra maestra desapareció antes del asesinato.', place:'LA GALERÍA DORADA' },
    'c05': { title:'Medianoche en el motel', desc:'La habitación 12 estaba cerrada por dentro.', place:'MOTEL STARLIGHT' },
    'c06': { title:'El último corte', desc:'El director lo llamó el final perfecto.', place:'ESTUDIOS SILVER SCREEN' },
  },
  ar: {
    'c01': { title:'توصيل على مدار الساعة', desc:'وصل طلب توصيل. ولم يغادر أحد الضيوف.', place:'الصفصاف والنبيذ' },
    'c02': { title:'الموت بالتخطيط', desc:'عرف المهندس المعماري كل طرق الخروج.', place:'منزل مورو' },
    'c03': { title:'ليلة هادئة', desc:'عاصفة واحدة. ستة ضيوف. بلا شهود.', place:'قصر بلاكثورن' },
    'c04': { title:'اختفاء الملهمة', desc:'اختفت تحفة فنية قبل وقوع الجريمة.', place:'المعرض المذهب' },
    'c05': { title:'منتصف الليل في الفندق', desc:'كان باب الغرفة 12 مقفلًا من الداخل.', place:'فندق ستارلايت' },
    'c06': { title:'المشهد الأخير', desc:'وصف المخرج النهاية بأنها مثالية.', place:'استوديوهات سيلفر سكرين' },
  },
  ru: {
    'c01': { title:'Доставка 24/7', desc:'Посылка прибыла. Один гость так и не ушёл.', place:'ИВА И ВИНО' },
    'c02': { title:'Смерть по проекту', desc:'Архитектор знал все выходы.', place:'ДОМ МОРРОУ' },
    'c03': { title:'Тихая ночь', desc:'Одна буря. Шесть гостей. Ни одного свидетеля.', place:'УСАДЬБА БЛЭКТОРН' },
    'c04': { title:'Пропавшая муза', desc:'Шедевр исчез до убийства.', place:'ЗОЛОТАЯ ГАЛЕРЕЯ' },
    'c05': { title:'Полночь в мотеле', desc:'Дверь номера 12 была заперта изнутри.', place:'МОТЕЛЬ «СТАРЛАЙТ»' },
    'c06': { title:'Последний дубль', desc:'Режиссёр назвал это идеальным финалом.', place:'СТУДИЯ «СИЛЬВЕР СКРИН»' },
  },
  'zh-CN': {
    'c01': { title:'全天候快递', desc:'快递送到了，一位客人却再没离开。', place:'柳树与葡萄酒' },
    'c02': { title:'设计之死', desc:'建筑师熟悉每一条出口路线。', place:'莫罗宅邸' },
    'c03': { title:'宁静之夜', desc:'一场风暴，六位客人，没有目击者。', place:'黑刺庄园' },
    'c04': { title:'失踪的缪斯', desc:'谋杀发生前，一件杰作消失了。', place:'鎏金画廊' },
    'c05': { title:'汽车旅馆午夜', desc:'12号房的门从里面反锁。', place:'星光汽车旅馆' },
    'c06': { title:'最后一剪', desc:'导演称这是完美的结局。', place:'银幕制片厂' },
  },
  'zh-TW': {
    'c01': { title:'全天候快遞', desc:'快遞送到了，一位客人卻再也沒離開。', place:'柳樹與葡萄酒' },
    'c02': { title:'設計之死', desc:'建築師熟悉每一條出口路線。', place:'莫羅宅邸' },
    'c03': { title:'寧靜之夜', desc:'一場風暴，六位客人，沒有目擊者。', place:'黑刺莊園' },
    'c04': { title:'失蹤的繆思', desc:'謀殺發生前，一件傑作消失了。', place:'鎏金畫廊' },
    'c05': { title:'汽車旅館午夜', desc:'12號房的門從裡面反鎖。', place:'星光汽車旅館' },
    'c06': { title:'最後一剪', desc:'導演稱這是完美的結局。', place:'銀幕製片廠' },
  },
};

const difficultyKey = { 'All':'all', 'Very Easy':'veryEasy', Easy:'easy', Medium:'medium', Hard:'hard', Expert:'expert' };
const monthNames = { JAN:'January', FEB:'February', MAR:'March', APR:'April', MAY:'May', JUN:'June', JUL:'July', AUG:'August', SEP:'September', OCT:'October', NOV:'November', DEC:'December' };

export function localeInfo(locale='en') {
  return locales.find(x => x.code === locale) || locales[0];
}

export function t(locale, key, values={}) {
  const selected = localeInfo(locale).code;
  const value = copy[selected]?.[key] ?? copy.en[key] ?? key;
  return value.replace(/\{(\w+)\}/g, (_, name) => values[name] ?? `{${name}}`);
}

export function difficultyLabel(locale, value) {
  return t(locale, difficultyKey[value] || value);
}

export function roomLabel(locale, value) {
  if (!value) return '';
  const selected = localeInfo(locale).code;
  if (typeof value === 'object') return value[selected] ?? value.en ?? '';
  const translated = copy[selected]?.rooms?.[value];
  return translated ?? value;
}

export function caseRoom(locale, puzzle, index) {
  if (!puzzle || index === undefined) return roomLabel(locale, puzzle?.areas?.[index]);
  const selected = localeInfo(locale).code;
  const translated = caseLocales[selected]?.[puzzle.id]?.areas?.[index];
  if (translated) return translated;
  if (index >= 3 && puzzle.areaSuffixes?.[index - 3]) {
    const base = roomLabel(locale, puzzle.areas[(index - 3) % 3]);
    return `${base} — ${translatedRoomSuffix(selected, puzzle.areaSuffixes[index - 3])}`;
  }
  return roomLabel(locale, puzzle.areas?.[index]);
}

export function roleLabel(locale, value, puzzle, personIndex) {
  if (!value) return '';
  const selected = localeInfo(locale).code;
  if (typeof value === 'object') return value[selected] ?? value.en ?? '';
  const fromCase = puzzle && caseLocales[selected]?.[puzzle.id]?.roles?.[value];
  const translated = fromCase ?? copy[selected]?.roles?.[value] ?? copy[selected]?.roles?.[value.toLowerCase()];
  return translated ?? value;
}

export function caseText(locale, puzzle, field) {
  const selected = localeInfo(locale).code;
  const source = puzzle?.[field];
  if (source && typeof source === 'object') return source[selected] ?? source.en ?? source['zh-CN'] ?? '';
  const data = caseLocales[selected]?.[puzzle?.id]?.[field];
  if (data) return data;
  const common = commonCaseCopy[selected]?.[puzzle?.id]?.[field];
  if (common) return common;
  if (field === 'difficulty') return difficultyLabel(locale, source);
  if (field === 'place') return source || '';
  return source || '';
}

export function formatDate(locale, source) {
  const match = String(source).match(/^([A-Z]{3})\s+(\d{1,2}),\s*(\d{4})$/i);
  if (!match) return source;
  const [, month, day, year] = match;
  const date = new Date(Date.UTC(Number(year), Object.keys(monthNames).indexOf(month.toUpperCase()), Number(day), 12));
  return new Intl.DateTimeFormat(localeInfo(locale).code, { year:'numeric', month:'short', day:'numeric', timeZone:'UTC' }).format(date);
}

export function clueText(locale, puzzle, clue) {
  if (!Array.isArray(clue?.constraints)) return clue?.text || '';
  const byType = Object.fromEntries(clue.constraints.map(item => [item.type, item.value]));
  const person = puzzle.people?.[clue.person];
  if (!person) return clue.text || '';
  const name = person[1] || person[0];
  const areaIndex = byType.area ?? byType.room;
  const room = caseRoom(locale, puzzle, areaIndex);
  const row = byType.row;
  const column = byType.column;
  const pair = byType.columnPair ?? byType.column_pair;
  const chunks = [];
  const localizedNumber = value => new Intl.NumberFormat(localeInfo(locale).code).format(value);
  if (row !== undefined || room) chunks.push(t(locale, 'clueRowRoom', { person: `${person[0]} · ${name}`, row: row === undefined ? '' : localizedNumber(row + 1), room }));
  if (column !== undefined) chunks.push(t(locale, 'clueColumn', { column: localizedNumber(column + 1) }));
  else if (pair !== undefined) {
    const anchorIndex = Array.isArray(puzzle.anchorByPair) ? puzzle.anchorByPair[pair] : ([0, 2, 4][pair]);
    const anchor = puzzle.people?.[anchorIndex]?.[1] || name;
    chunks.push(t(locale, 'clueColumnPair', { start:pair * 2 + 1, end:pair * 2 + 2, anchor }));
  }
  if (person[2] && puzzle.id === 'c01' && clue.person < 5) chunks.push(t(locale, 'clueRole', { role:roleLabel(locale, person[2], puzzle, clue.person) }));
  if (person[0] === 'V') chunks.push(t(locale, 'clueVictim'));
  return chunks.length ? chunks.join(' ') : clue.text || '';
}

export function supportedLocale(locale) {
  return locales.some(item => item.code === locale) ? locale : 'en';
}
